name: Publish 🚀

on:
  workflow_dispatch:
  push:
    branches:
    - main

env:
  AZURE_WEBAPP_NAME: Pet-Store-Aug
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"

jobs:
  publish:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: set env 
        env:
          ASPNETCORE_ENVIRONMENT: "Production"
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          
      - name: Restore
        run: dotnet restore ./PetStore/PetStore.sln
        
      - name: Build
        run: dotnet build ./PetStore/PetStore.sln --configuration Release --no-restore
        
      - name: Publish
        run: dotnet publish ./PetStore/PetStore.sln --configuration Release --no-build --output '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
        
      - name: Deployment
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_7C104A95AC964559AA22350E40F62546 }}
          package: "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
